export {default as MovieDetails} from './moveDetails'
export {default as Casting} from './Casting'
export {default as Trailer} from './Trailer'
export {default as MoveDetailsSkeleton} from './moveDetailsSkeleton'
export {default as CastingSkeleton} from './Casting/CastingSkeleton'
export {default as TrailerSkeleton} from './Trailer/TrailerSkeleton'